### ISSUE TITLE
Unexpected log "Ordering took too long..."

### ISSUE THREAD

**Issue by sp-adan-lobato** [paulfitz/daff-php#14]
The log message is being generated here:
https://github.com/paulfitz/daff-php/blob/master/gen/lib/coopy/Alignment.class.php#L159

We're comparing the following tables:
```
Array
(
    [0] => Array
        (
            [0] => lorem
            [1] => ipsum
        )

    [1] => Array
        (
            [0] => 1
            [1] => value
        )

    [2] => Array
        (
            [0] => 2
            [1] => value
        )

)
```
```
Array()
```

Result:
```
Alignment.hx:153: Ordering took too long, something went wrong
[["@:@",null,"0:-","1:-"],[null,"!","---","---"],[null,"@@","lorem","ipsum"],["1:-","---",1,"value"],["2:-","---",2,"value"]]
```

The diff generated is completely correct, but the log message being generated is printed to output and the resulting page is wrong.

**Comment by paulfitz** [comment]
This does seem fixed in current version, please reopen if not.

**Comment by gonzaloserrano** [comment]
I got a ```Alignment.hx:277: Ordering took too long, something went wrong```here:

https://www.dropbox.com/s/iibwhm57tmb359e/Screenshot%202015-03-04%2018.24.01.png?dl=0

**Comment by paulfitz** [comment]
@gonzaloserrano do you happen to have the original tables being compared when this happened?

**Comment by gonzaloserrano** [comment]
Hi! After some searching i found the tables and i could reproduce it, you can find the test here: https://gist.github.com/gonzaloserrano/8ecdecb04179f688ef4b

**Comment by gonzaloserrano** [comment]
This problem is still present in 1.2.7

**Comment by paulfitz** [comment]
yup I have a partial fix for this in hand but not finished.

**Comment by paulfitz** [comment]
There have been improvements in 1.2.8.

**Comment by gonzaloserrano** [comment]
Yes, now it runs as expected, thank you very much.
