### ISSUE TITLE
PSR-0 / PSR-4 autoloader

### ISSUE THREAD

**Issue by dogmatic69** [paulfitz/daff-php#7]
Continue from #5 as that was initially something else.

PSR-0 examples

    \Doctrine\Common\IsolatedClassLoader => /path/to/project/lib/vendor/Doctrine/Common/IsolatedClassLoader.php
    \Symfony\Core\Request => /path/to/project/lib/vendor/Symfony/Core/Request.php
    \Zend\Acl => /path/to/project/lib/vendor/Zend/Acl.php
    \Zend\Mail\Message => /path/to/project/lib/vendor/Zend/Mail/Message.php

Or skip to PSR-4

| Fully Qualified Class Name    | Namespace Prefix   | Base Directory           | Resulting File Path
| ----------------------------- |--------------------|--------------------------|-------------------------------------------
| \Acme\Log\Writer\File_Writer  | Acme\Log\Writer    | ./acme-log-writer/lib/   | ./acme-log-writer/lib/File_Writer.php
| \Aura\Web\Response\Status     | Aura\Web           | /path/to/aura-web/src/   | /path/to/aura-web/src/Response/Status.php
| \Symfony\Core\Request         | Symfony\Core       | ./vendor/Symfony/Core/   | ./vendor/Symfony/Core/Request.php
| \Zend\Acl                     | Zend               | /usr/includes/Zend/      | /usr/includes/Zend/Acl.php

**Comment by paulfitz** [comment]
Closing as a non-priority that no-one is clamoring for, thanks @dogmatic69.
